kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: monitoring-grafana-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: mynfs